# --- !Ups

create table "products" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"ean" BIGINT NOT NULL,"name" VARCHAR NOT NULL,"description" VARCHAR);

# --- !Downs

drop table "products";

