# --- !Ups

create table "redirects" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"uid" VARCHAR NOT NULL,"iurl" VARCHAR NOT NULL,"qargs" VARCHAR NOT NULL,"rurl" VARCHAR NOT NULL);
 
# --- !Downs

drop table "redirects";

